### ISSUE TITLE
Add donation button

### ISSUE THREAD

**Issue by athackst** [womeninrobotics/womeninrobotics.github.io#10]

**Comment by athackst** [comment]
@andrakan Do we have anything set up to accept donations?

**Comment by andrakan** [comment]
We could send to Silicon Valley Robotics - because technically that's where we're processing things atm - I'll set up a paypal button code in a sec.

**Comment by andrakan** [comment]
Here's code for Paypal button https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7QBGVMNX4QMS8
atm it's a work around - Women in Robotics is listed as one of the programs that donors can select. Will do for now.

**Comment by athackst** [comment]
Done!
