### ISSUE TITLE
Link to all social media accounts

### ISSUE THREAD

**Issue by athackst** [womeninrobotics/womeninrobotics.github.io#11]

**Comment by athackst** [comment]
@andrakan Do we have any other social media accounts that I'm missing?

**Comment by andrakan** [comment]
I think we have Insta - and Twitter - Facebook - Pinterest perhaps - I'll do a survey

**Comment by andrakan** [comment]
Our social is:
Facebook - https://www.facebook.com/womeninrobotics/
Twitter - https://twitter.com/womeninroboticz/
Instagram - https://www.instagram.com/womeninroboticz/
Pinterest - not there yet but will either be womeninrobotics OR the alternative womeninroboticz
Linked In - https://www.linkedin.com/groups/7072127/
(I can't find a way to get the name not the numbers yet on LI - and I've just changed the insta to be same as twitter as we can't get womeninrobotics on either platform)
