### ISSUE TITLE
Add analytics tracking

### ISSUE THREAD

**Issue by athackst** [womeninrobotics/womeninrobotics.github.io#12]

**Comment by athackst** [comment]
@andrakan Do we already have a google analytics tracking ID?

**Comment by andrakan** [comment]
only on SVRobo - Robohub - etc. Will follow up.

**Comment by andrakan** [comment]
I've just set up google analytics for website (and new beta - can do ios and android too). Here's the tracking code for head of every page.

<script async src="https://www.googletagmanager.com/gtag/js?id=G-2V4NNSWC1S"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-2V4NNSWC1S');
</script>

**Comment by andrakan** [comment]
Should I have pasted that in a different way? I'm pretty new to this.

**Comment by athackst** [comment]
It's cool, I just needed the ID.

FYI to do code-blocks you need type three \` before and after like
 \`\`\` 
{code}
\`\`\`

**Comment by athackst** [comment]
It should be live now if you want to test
