### ISSUE TITLE
Point Womeninrobotics.org to new github site!

### ISSUE THREAD

**Issue by andrakan** [womeninrobotics/womeninrobotics.github.io#14]

**Comment by andrakan** [comment]
Both womeninrobotics.org and womeninrobotics.com have been redirected to womeninrobotics.github.io/

**Comment by athackst** [comment]
Cool!

There's some extra info in config, github settings, and CNAME that should also be updated to fully close this.

**Comment by andrakan** [comment]
Okeydoke - rather than a redirect I guess.

**Comment by athackst** [comment]
Redirect works for now.

I assume we want the address bar to read `womeninrobotics.org` and not `womeninrobotics.github.io`

Does that sound right?

**Comment by athackst** [comment]
@andrakan You will need to update the DNS record of whichever address you want to make primary following these directions: 

I recommend using configuring it as a subdomain and using www 

https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain
