### ISSUE TITLE
Integrated form for community signup

### ISSUE THREAD

**Issue by athackst** [womeninrobotics/womeninrobotics.github.io#16]
Currently, we link out to a google form to sign up for the community.

Transfer functionality to the website

**Comment by reyhanehpahlevan** [comment]
I embedded the current form until we decide how we should implement it
https://womeninrobotics.github.io/signup/

**Comment by andrakan** [comment]
Thanks. I've improved the form somewhat but haven't implemented the more coordinated approach Allison suggested. I'm happy with this for now.
