### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by athackst** [womeninrobotics/womeninrobotics.github.io#18]
Create a 404.html page.

This is a good issue to begin learning about Jekyll, HTML and CSS.

1. Create a 404.html page in the main folder.
2. Design how the page should look using the default template by putting the following snippet at the top of your file

```yaml
---
layout: default
title: 404
---
```
3. Design how the 404 page should look!

When you open a PR, a preview will automatically be generated for review by the maintainers.

**Comment by Jidnyasa-git** [comment]
Hi, I want to work on this issue. Can you assign it to me ?
