### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by athackst** [womeninrobotics/womeninrobotics.github.io#2]
About page should contain the following information:

- What is Women in Robotics
- Link outs to other groups (K-12,etc)
- How to support
- Board of directors

**Comment by reyhanehpahlevan** [comment]
"about.html" could be found in "pages" directory. I will try to fill it with some information to be edited later

**Comment by athackst** [comment]
Cool! Could you PR it when you add info? It would be good to get feedback from @andrakan before it's submitted.

**Comment by reyhanehpahlevan** [comment]
Yes! We need to discuss it's designed first, I couldn't find an about us sample page for this theme! If it's not containing correspond elements we need to choose the preferred design first and then bring its extra layout and styles.

**Comment by andrakan** [comment]
Our social is:
Facebook - https://www.facebook.com/womeninrobotics/
Twitter - https://twitter.com/womeninroboticz/
Instagram - https://www.instagram.com/womeninroboticz/
Pinterest - not there yet but will either be womeninrobotics OR the alternative womeninroboticz
Linked In - https://www.linkedin.com/groups/7072127/
(I can't find a way to get the name not the numbers yet

**Comment by athackst** [comment]
@reyhanehpahlevan Do you want to take point on the about page?

**Comment by andrakan** [comment]
https://docs.google.com/document/d/1toc_yYfv8lvXb9RWTIEq82EH0eRUq5zF6pDK29c_Vvc/edit?usp=sharing

Text for About Us, Advisory Board and Call to Action pages
