### ISSUE TITLE
White WIR logo

### ISSUE THREAD

**Issue by athackst** [womeninrobotics/womeninrobotics.github.io#4]
Make WIR logo white for usage in footer

**Comment by andrakan** [comment]
![WIR_spanner_WIR 2](https://user-images.githubusercontent.com/4812505/95667690-4c2eec00-0b1e-11eb-9d21-42bb8a184425.png)
![WIR_spanner_White](https://user-images.githubusercontent.com/4812505/95667692-5355fa00-0b1e-11eb-8dcd-17b6456db4ec.png)
One is just the spanner. the first WIR_spanner_WIR has small Women in Robotics text
