### ISSUE TITLE
Sponsor section needed

### ISSUE THREAD

**Issue by andrakan** [womeninrobotics/womeninrobotics.github.io#47]
Our first corporate sponsor is Robust.ai
But we also receive support equivalent from Silicon Valley Robotics, Robohub.org, CITRIS CPAR.
I have most of the logos in either white, black or color format.

**Comment by athackst** [comment]
Cool, I was envisioning putting sponsors in the "support" section.  Feel free to upload the images.

**Comment by andrakan** [comment]
Fantastic. Thanks for making this happen and documenting it so that we can
make updates as and when needed. best, Andra

***

Andra Keay : she/her/hers : *andrakeay@gmail.com <andrakeay@gmail.com>*  w:
+1.650.204.0003
Managing Director : Silicon Valley Robotics <http://svrobo.org/> :
andra@svrobo.org
Visiting Scholar: CITRIS People and Robots
<https://citris-uc.org/people-and-robots/> : andra@berkeley.edu
Visit us at: Circuit Launch <https://circuitlaunch.com/> 8000 Edgewater Dr
Oakland CA
Sign up for the Silicon Valley Robotics newsletter <http://eepurl.com/phi2P> -
your guide to robotics news & events.
Subscribe to the Silicon Valley Robotics Youtube Channel
<https://www.youtube.com/channel/UCP3DjaUKGYPqospiPaxbVBQ?view_as=subscriber>
- catch our events and browse robotics playlists

**Comment by andrakan** [comment]
Please add Manager (title of your choice) Women in Robotics website as a
volunteer project/position on LI if you'd like. best, Andra

***

Andra Keay : she/her/hers : *andrakeay@gmail.com <andrakeay@gmail.com>*  w:
+1.650.204.0003
Managing Director : Silicon Valley Robotics <http://svrobo.org/> :
andra@svrobo.org
Visiting Scholar: CITRIS People and Robots
<https://citris-uc.org/people-and-robots/> : andra@berkeley.edu
Visit us at: Circuit Launch <https://circuitlaunch.com/> 8000 Edgewater Dr
Oakland CA
Sign up for the Silicon Valley Robotics newsletter <http://eepurl.com/phi2P> -
your guide to robotics news & events.
Subscribe to the Silicon Valley Robotics Youtube Channel
<https://www.youtube.com/channel/UCP3DjaUKGYPqospiPaxbVBQ?view_as=subscriber>
- catch our events and browse robotics playlists
