### ISSUE TITLE
Update chapter list

### ISSUE THREAD

**Issue by athackst** [womeninrobotics/womeninrobotics.github.io#5]
Transfer entire chapter list from https://svrobo.org/women-in-robotics/ to [_data/chapters.yaml](https://github.com/womeninrobotics/womeninrobotics.github.io/blob/main/_data/chapters.yaml)

**Comment by andrakan** [comment]
I updated it a couple of days ago so should be up to date - for the moment!

**Comment by andrakan** [comment]
Melbourne chapter in Australia can be added now
https://meetingplace.io/womeninroboticsmelbourne
