### ISSUE TITLE
Improve the LinkedIn social media card 

### ISSUE THREAD

**Issue by athackst** [womeninrobotics/womeninrobotics.github.io#75]
The current card crops the WiR logo.

**Comment by athackst** [comment]
@xLisax Any interest in creating a better default card image?

**Comment by rocklikereeju00** [comment]
Can I work in this project ?

**Comment by athackst** [comment]
Sure! Let me know if you need any help.

**Comment by rocklikereeju00** [comment]
"The current card crops the WiR logo." mean ? Please tell me in details.
"Improve the LinkedIn social media card"  mean ? Change any color or otherthinks ? Please hlep me here !

**Comment by athackst** [comment]
This is what the current card looks like:

![WiRLinkedIn](https://user-images.githubusercontent.com/6098197/106394139-ece83680-63af-11eb-8b9f-6e1fa63e3d92.png)

## LinkedIn image guidelines:

### LinkedIn link share images

Use a 1.91:1 ratio (1200×627 px).
Image must be more than 200px wide.

If your image width is less than 200px, it will appear as a thumbnail on the left side of the post.
> I believe this is what is happening to the logo
 
Note: This doesn’t apply if you’re posting an image only or an image and text. The image will be enlarged to fit the feed.
Images on mobile won’t be cropped. Images of other ratios will show in full with subtle white padding.

### LinkedIn post image size

LinkedIn photo post size seems difficult to determine.

Based on some discussions on the internet, it seems like 1584x1056 px might be the best size.

1200 x 1200 square looks best on desktop, but gets cropped to horizontal in the mobile feed.

## The task
@xLisax will be creating some new art for us
@rocklikereeju00 will need to update the code to use a specified image.  Right now it's unset.

File:
```
_layouts
|____ default.html
```
Relevant lines:
```html
  <meta property="og:title" content="{{ page.title }}">
  <meta property="og:description" content="{{ page.tagline }}">
  <meta property="og:image" content="{{ page.image }}">
  <meta property="og:url" content="{{ site.url }}">
  <meta name="twitter:card" content="summary_large_image">
```
It's currently looking for "page.image" which doesn't exist.  The output of our website looks like:
```html
  <meta property="og:title" content="Home">
  <meta property="og:description" content="">
  <meta property="og:image" content="">
  <meta property="og:url" content="https://womeninrobotics.org">
  <meta name="twitter:card" content="summary_large_image">
```

1. Update the jekyll to use `site.image` if `page.image` doesn't exist
2. Add `image: <file>` to `_config.yml` and update that file name with the media @xLisax creates.  For now we can probably use `/assets/images/WIR_banner_wide.png`

**Comment by xLisax** [comment]
I created a folder with different sizes of the WiR logo in gDrive. Look under 'Artwork Committee/Art Files/WiR logo'. If you don't find what you need let me know and I can make a specific size.

**Comment by athackst** [comment]
Thanks!  I've added the logos to the site in #77

**Comment by athackst** [comment]
@rocklikereeju00 the card still needs to be updated if you're still interested?

**Comment by rocklikereeju00** [comment]
Sorry, @athackst  my P.C. in very bad condition . I work in my mobile , so I can't contribute on this project .
