### ISSUE TITLE
Add guest writers to webstie

### ISSUE THREAD

**Issue by arii** [womeninrobotics/womeninrobotics.github.io#76]
Showcase prominent volunteer members such as Sunita who has authored 8 features 

https://robohub.org/archives/authors/sunitapokharel/

**Comment by athackst** [comment]
What's the right way to showcase authors/volunteers?  Write an article?  Creat an authors page?

**Comment by andrakan** [comment]
i think an authors page is a great idea now that we're getting more women writing posts, interviews and articles.

**Comment by athackst** [comment]
Do we have a list of authors?

**Comment by athackst** [comment]
This is closed by #255
