### ISSUE TITLE
Add post for WiR list 2013

### ISSUE THREAD

**Issue by athackst** [womeninrobotics/womeninrobotics.github.io#8]
Transfer link and image from https://svrobo.org/women-in-robotics/ for previous WiR news articles.

Posts are created in [_posts)(https://github.com/womeninrobotics/womeninrobotics.github.io/tree/main/_posts).
Images are saved in [assets/images/news](https://github.com/womeninrobotics/womeninrobotics.github.io/tree/main/assets/images/news)

Add a new file with the format `YYYY-MM-dd-Title.md` 
and the following front matter:

```yaml
---
layout: default
title: 
image: 
link: 
---

**Comment by andrakan** [comment]
2013 original link on Robohub.org https://robohub.org/25-women-in-robotics-you-need-to-know-about/
2014 original link on Robohub.org https://robohub.org/25-women-in-robotics-you-need-to-know-about-2014/
2015 original link on Robohub.org https://robohub.org/25-women-in-robotics-you-need-to-know-about-2015/
2016 ... irritated that it was reposted in 2017 changing the date! but you've got it already!
I will try to follow directions for adding.
