### ISSUE TITLE
Use Netlify for deploys

### ISSUE THREAD

**Issue by athackst** [womeninrobotics/womeninrobotics.github.io#82]
Netlify offers several good features for the website that we should take advantage of:

1. [Form submissions](https://docs.netlify.com/forms/setup/) To natively support form submissions and workflows within the website including custom notifications, thank you pages, and [Zapier](https://www.netlify.com/blog/2018/11/07/automate-your-netlify-sites-with-zapier/) for automatic workflows

2. [Netlify CMS](https://www.netlifycms.org/) To make it easier for non-webdevs to edit the site

Cons for implementing this feature:
- Need to switch hosts
- Possible over-reliance on third party services

## Task list

- [x] Transfer to netlify DNS
- [x] Setup CMS

**Comment by andrakan** [comment]
Hi Allison, Are we able to do this on the free plan or will we need to
upgrade? That's my main question. best, Andra

*****
*Andra Keay : she/her/hers :* *andrakeay@gmail.com <andrakeay@gmail.com>*  w:
+1.650.204.0003
Join womeninrobotics.org : @womeninroboticz
<http://twitter.com/womeninroboticz> : Women in Robotics newsletter
<https://sendfox.com/womeninrobotics>
Visiting Scholar: CITRIS People and Robots
<https://citris-uc.org/people-and-robots/> : andra@berkeley.edu
Managing Director : Silicon Valley Robotics <http://svrobo.org/> :
andra@svrobo.org : @svrobo <http://twitter.com/svrobo>
SVR Startup Accelerator and CoLAB at: Circuit Launch
<https://circuitlaunch.com/> 8000 Edgewater Dr Oakland
Latest robotics news & events at: Silicon Valley Robotics newsletter
<https://sendfox.com/svrobo>
*A Founding Member Of*

**Comment by athackst** [comment]
At our current state I think our usage should be well within the usage limits on the free account.

**Comment by athackst** [comment]
We've transferred to netlify for deploys
