### ISSUE TITLE
Project Advance links broken

### ISSUE THREAD

**Issue by andrakan** [womeninrobotics/womeninrobotics.github.io#95]
I suggest this text as the Submit link: 
Submit an application to mentor or be a mentee (you can be both)
and here's the form link:
https://docs.google.com/forms/d/e/1FAIpQLSfGEyVUtbOPus2ckF-z7pweEdUq6AEqAaEgaXx9Mh7UkZG38w/viewform?usp=sf_link

**Comment by athackst** [comment]
I don't understand what links are broken?  The link to the form on the site is the same as that one.  The only thing that looks like it's missing is a link to project-advance from the about page (fixed in #96)

Maybe the permissions on the form need to be updated?
